<a href="https://colab.research.google.com/github/s-ravi18/my_reference/blob/main/PyTorch_Tuts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# Basics:

Main functions:

- torch.tensor() - a.shape,a.ndim,a.dtype,a.device,torch.reshape(a,target)

- tensor-->(dtype,device,requires_grad) 

- a.type(target_dtype), max(), min(), sum(), mean(), torch.argmax()/argmin() - aggregation and type conversion

- torch.matmul()

- a.copy(),a.view()

- torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.

  torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

- Reproducability: torch.manual_seed(seed=RANDOM_SEED) 

Note: The lower the precision of the datatype, the higher the speed of computation but trades off against accuracy. eg: 8 bit performs faster than 16 bit. Saves memory too. 

In [ ]:
## Checking version:
torch.__version__

'1.13.1+cu116'

In [ ]:
a=torch.tensor(5)  ## Creating a scalar
a
a.ndim  # To check the dimension
a.item()

5

In [ ]:
a=torch.Tensor(10)
a

tensor([ 1.7399e-17,  4.5593e-41,  1.7404e-17,  4.5593e-41,  1.7400e-17,
         4.5593e-41, -4.2503e+18,  4.5593e-41,  1.7340e-17,  4.5593e-41])

In [ ]:
a=torch.tensor([[1,2,3,4],[1,2,3,4]]) ## Pass in a array of numbers=> vector
a=torch.tensor([1,2,3,4],dtype=torch.float16,device=None,requires_grad=False)
a.ndim
a.shape

torch.Size([4])

In [ ]:
a=torch.rand(size=(3, 4, 5)) ## Random vectors
a.ndim
a.shape
a.dtype

torch.float32

In [ ]:
a=torch.zeros(size=(3, 4))
a=torch.ones(size=(3, 4))
a=torch.arange(5)
a

tensor([0, 1, 2, 3, 4])

In [ ]:
%%time
## Tensor operations
## Dot Product:
a=torch.tensor([1,2,3,4])
b=torch.tensor([1,2,3,4])
torch.matmul(a,b)
##Element wie Multiplication:
a*b

CPU times: user 1.05 ms, sys: 2 µs, total: 1.06 ms
Wall time: 838 µs


tensor([ 1,  4,  9, 16])

In [ ]:
## Aggregation:
a.min(),a.max(),a.type(torch.float32).mean(),a.sum()
torch.argmax(a),torch.argmin(a)  ## returns the index of the resp. max and min elements

(tensor(3), tensor(0))

In [ ]:
## Changing the type of a tensor:
a.type(torch.float16)

tensor([1., 2., 3., 4.], dtype=torch.float16)

In [ ]:
# Check for GPU
torch.cuda.is_available()
# Count number of devices
torch.cuda.device_count()
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device
# Putting tensors on GPU:
some_tensor=torch.tensor([1,2,3,4])
some_tensor = some_tensor.to(device)
# Tensor back to cpu and into numpy array:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

AutoGrad:: Built-in differentiation engine. 

Parameters of your ML Model will require "requires_grad" paramter to be True.
For eg: w = torch.randn(5, 3, requires_grad=True)
        b = torch.randn(3, requires_grad=True)


To compute gradients:
- define the loss function in term of the parameters
- use .backward() method i.e. loss.backward()
- finally retrieve the individual gradients of the parameters using .grad attribute.

For eg:
loss.backward(),
w.grad,
b.grad

Grad is only available for those which have requires_grad=True



In [ ]:
## Making a Prediction:

with torch.inference_mode(): 
    y_preds = model(X_test)

# Note: in older PyTorch code you might also see torch.no_grad()

# with torch.no_grad():   #### IMPORTANT
#   y_preds = model_0(X_test)

**Loss functions:**

torch.nn.L1loss()   ---> MAE for Regression

torch.nn.BCEloss()  ---> Binary Cross Entropy for Binary classification

**Optimizers:**

torch.optim.SGD()

torch.optim.Adam()

In [ ]:
torch.optim.SGD(params=model.parameters(),lr=0.001)   ## Two parameters - (model parameters,learning rate)

# Simple Demonstration:

Steps to follow:

1. Data Definition and conversion into tensors
2. Define the model class with paramters and forward function
3. Training:
*   Define the loss and optimisers
*   Calculate the forward pass and back propagate the loss fn
4. Make a new prediction
5. Saving and Loading a model

In [ ]:
## STEP 1: CREATING THE DATA
# Create weight and bias
weight = 0.7
bias = 0.3

# Create range values
start,end,step = 0,1,0.02

# Create X and y (features and labels)
X = torch.arange(start, end, step).unsqueeze(dim=1) # without unsqueeze, errors will happen later on (shapes within linear layers)
y = weight * X + bias 
X[:10], y[:10]

# Split data
train_split = int(0.8 * len(X))
X_train, y_train = X[:train_split], y[:train_split]
X_test, y_test = X[train_split:], y[train_split:]

len(X_train), len(y_train), len(X_test), len(y_test)

In [ ]:
## STEP 2: MODEL DEFINITION:
class LR(nn.Module):
  def __init__(self):
    super().__init__()    ### This ensures that all the base class methods and variables are accessible.

# Note:Calling the previously built methods with super() saves you from needing to
# rewrite those methods in your subclass, and allows you to swap out superclasses with minimal code changes.

In [ ]:
class Base(object):
    def __init__(self):
        print("Base created")
        
class ChildA(Base):
    def __init__(self):
        Base.__init__(self)
        
class ChildB(Base):
    def __init__(self):
        super(ChildB, self).__init__()
        
ChildA() 
ChildB()

Base created
Base created
